<?php $theme = \Wwm\Blog\Cms\WordPress\ThemeFactory::getInstance(); ?>
<form action="<?php echo $theme->escUrl($theme->setUrlScheme($theme->getHomeURLNew() . '/wp-login.php?action=postpass', 'login_post')); ?>" method="post" class="post-password-form" data-hasrequired="<?php $theme->_e('* Required Fields'); ?>" novalidate="novalidate" data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <legend class="legend"><?php $theme->_e('This content is password protected. To view it please enter your password below:'); ?></legend>
        <div class="field required">
            <label class="label" for="post-password"><span><?php $theme->_e('Password:'); ?></span></label>
            <div class="control">
                <input type="password" name="post_password" id="post-password" class="input-text" value="" size="20" required="required" aria-required="true" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" class="action submit primary"><span><?php echo $theme->escAttrX('Enter', 'post password form'); ?></span></button>
            </div>
        </div>
    </fieldset>
</form>
