<button type="button" onclick="installWordPressTheme()">
    <span><?php echo __('Install Theme'); ?></span>
</button>
<script>
require([
    'underscore',
    'Magento_Ui/js/modal/alert',
    'prototype'
], function (_, alert) {
    function installWordPressTheme() {
        var result;
        new Ajax.Request("<?php echo $block->getUrl('wwm_blog/system_config/themeinstall'); ?>", {
            onSuccess: function(response) {
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                } catch (e) { }
            }.bind(this),
            onComplete: function(response) {
                if (!_.isString(result)) {
                    result = "<?php echo __('Unknown error'); ?>";
                }
                alert({content: result});
            }.bind(this)
        });
    };
    window.installWordPressTheme = installWordPressTheme.bind(installWordPressTheme)
})
</script>
