<?php global $theme; ?>
<div class="field comment-form-comment required">
    <label class="label" for="comment"><span><?php $theme->_ex('Comment', 'noun'); ?></span></label>
    <div class="control">
        <textarea id="comment" class="input-text" name="comment" cols="45" rows="8" maxlength="65525" aria-required="true" required="required" data-validate="{required:true}"></textarea>
    </div>
</div>
